blank_issues_enabled: false

contact_links:
  - name: ðŸ’¬ Support Question
    url: https://github.com/Dictionarry-Hub/database/discussions/new?category=q-a
    about: Ask questions and get help from the community

  - name: ðŸ“š Check the Docs
    url: https://dictionarry.dev
    about: Read the documentation before opening an issue
